### ISSUE TITLE
Unable to obtain IOS local network permissions

### ISSUE THREAD

**Issue by guojunlong** [Nimrodda/flutter_nsd#14] opened 2021-09-23 07:37 UTC
I have set "Bonjour services" and "privacy - local network usage description" in info.plist according to the requirements of "note about IOS" in readme in “Flutter-nsd1.2.0", but I still can't obtain local network permissions,But android already does this,Is there anything else I haven't set up on ios?

Bonjour Services:   "_connect1._tcp.”

The version number of my ios device is 14.7.1, and the model is iPhone6s Plus

**Comment by Nimrodda** [comment] 2021-09-23 08:20
Have you tried with iOS version before 14?

**Comment by guojunlong** [comment] 2021-09-23 10:16
> Have you tried with iOS version before 14?
> […](#)

The version number of my ios device is 14.7.1, and the model is iPhone6s Plus

**Comment by Nimrodda** [comment] 2021-09-23 13:53
Please try on iOS simulator that runs iOS lower than 14. For example iOS 11. The requirement to add these entries in info.plist is only for iOS 14+. If it works on older versions then the issue is in your info.plist configuration.

**Comment by guojunlong** [comment] 2021-09-23 14:08
> Please try on iOS simulator that runs iOS lower than 14. For example iOS 11. The requirement to add these entries in info.plist is only for iOS 14+. If it works on older versions then the issue is in your info.plist configuration.

I tried to run the overload ios Simulator today, and I can get the local network permission. According to what you said, the problem should be in my info.plist file. Could you please help me find out what the problem is?

<img width="697" alt="截屏2021-09-23 下午10 07 50" src="https://user-images.githubusercontent.com/12324650/134522455-e8a2f9b0-344e-42dc-a9c8-8e0d8fa7f881.png">

**Comment by Nimrodda** [comment] 2021-09-23 17:13
Looks about right. Have you tried with the example app?

**Comment by guojunlong** [comment] 2021-09-23 18:25
> Looks about right. Have you tried with the example app?
> […](#)

Yes, I created a Flutter project and tested this function separately. Could you please help me find out what the problem is?

The device is iPhone 6S Plus and the system is 14.7.1. After running, click "Start" and there is no prompt for local network authorization.


[https://github.com/guojunlong/untitled_test_nsd.git](https://github.com/guojunlong/untitled_test_nsd.git)

**Comment by Nimrodda** [comment] 2021-09-24 11:54
I did a quick test with the example app and indeed I don't see the prompt on my iPhone. Nevertheless, it shows that Local Network permission is granted under Settings->Privacy->Local Network. I'll have to investigate this. Please let me know if you find anything. Thanks!

**Comment by guojunlong** [comment] 2021-09-24 13:34
> I did a quick test with the example app and indeed I don't see the prompt on my iPhone. Nevertheless, it shows that Local Network permission is granted under Settings->Privacy->Local Network. I'll have to investigate this. Please let me know if you find anything. Thanks!


Yes, I found the problem, you were right before, it is the info.plist file, it is the problem of "NSBonjourServices", open the info.plist file as "Source Code" and find
“Bonjour Services", change the Key value to "NSBonjourServices", and then run again to get the prompt of local network permission, but why the project does not recognize "BonjourServices", I do not know. If you know the reason, please tell me. Thank you

**Comment by Nimrodda** [comment] 2021-09-24 13:57
That's a great discovery and thank you so much for sharing it here. I wonder if this is a bug in latest Xcode or something. It should be possible to add it via the UI as well 🤔

**Comment by Nimrodda** [comment] 2021-09-25 06:30
Which version of Xcode are you using? Mine is version 13.0 (13A233). For now I updated the README.md with example XML from Info.plist. I filed a [bug report](https://feedbackassistant.apple.com/feedback/9652950) to Apple .

**Comment by guojunlong** [comment] 2021-09-25 06:34
> 13.0 (13A233).

I use the same Xcode as your version, also 13.0 (13A233).

**Comment by Nimrodda** [comment] 2021-09-25 06:52
Are you able to reproduce this issue? Now when I add Bonjour Services via the UI and then inspect the source code it seems to be correct everytime. Really weird.

**Comment by guojunlong** [comment] 2021-09-25 09:49
I use Xcode (13.0 (13a233)), test model: iPhone 6S plus, mobile phone system: 14.7.1,

When I add the key value “Bonjour Services" and the corresponding value in the string "Bonjour Services" through “Property List" or “Source Code", I will not be able to obtain the local network permission. However, if I add the key "Bonjour Services" and the corresponding value in the string “NSBonjourServices", Everything is normal. The difference between the two adding methods is that when we check the source code of info.plist, the key values are "Bonjour Services" and “NSBonjourServices"

I just tried, and the problem still exists

**Comment by Nimrodda** [comment] 2021-09-25 09:56
Thanks for trying. I filed a bug report to Apple. Let's hope they fix it
soon.

**Comment by guojunlong** [comment] 2021-10-10 12:20
Originally, everything was normal, but when I needed to integrate the project into plugin packages, I could not obtain the local network permission in the ios environment. This time, the modification of the Key value did not work, but it still works in the Android environment,   

Do you have any ideas on how to solve this situation?
@Nimrodda

**Comment by Nimrodda** [comment] 2021-10-10 14:04
My assumption is that you're facing the same issue you faced before in Xcode. Make sure that the source code of Info.plist indeed has the right piece of code there with the correct domain etc.

I'm closing this issue since it's not an issue in the plugin.

**Closed as completed by Nimrodda** 2021-10-10 14:04 UTC
